### PR TITLE
Reaconstruct

### PR DESCRIPTION
**Pull request by GantMan**
this takes care of #31 and #23 

Semaphore CI will fail because of the folder changes.   I will fix semaphore after this is merged.

### CODE REVIEW

**Comment by skellock** [comment]
Can we ignore .node_modules?

**Comment by GantMan** [comment]
@skellock UGH, sorry to commit that.   Damn .gitnigore wasn't in the right place.

I know technically I should remove this from git history, but I don't think it's a huge hit to the repo size.

**Comment by GantMan** [comment]
@skellock if you disagree, I'll scrap this branch and start over.

Also, for some reason, file history didn't come over in the rename.

**Comment by skellock** [comment]
It's all good.   I just looked at the 11,000+ changed files and shit myself.

Let's roll!

**Pull request merged**
