### PR TITLE
Adds example of setting a nav bar button.

### PR DESCRIPTION
**Pull request by markrickert**
Tests?

no

### CODE REVIEW

**Comment by skellock** [comment]
Tests are ... uh ... complicated for React Native.   I'm sure it won't be in a few months, but right now, for any file that imports `react-native`, you must stub the universe.

(Because RN requires JSC and our desktops run Node.js.  I'm sure there's more to it, but that's as much as I care to know.)

Thanks for the PR's!

**Comment by GantMan** [comment]
I'll bring in Mocha for tests and shallow render, I don't mind.   The only issue is we carry the cognitive load if we do.   In my opinion, it's better than no tests on components, and we can strip them out when we get there.

**Comment by skellock** [comment]
We're mocha-ified already!  I don't think we have examples of chai & jsx assertions just yet.  Did you end up using Enzyme on your client's project?

If we have to change our non-test code to support the crazy mocking, we've gone too far though. (imho)

But yes, you're correct.  It's better than no tests.   :heart_eyes_cat:

**Comment by GantMan** [comment]
We'd only have to change the code if we start using `.ios.js` and `.android.js`  OR we can update the compiler to look for those files if it fails to find regular `.js` files.   All good stuff.  In any case we're clear to use it for now.

Yes, I used Enzym on the client project.  Works great, but I'm a complete idiot when I'm returned virtual dom info.   Takes me a while to write a good test.

**Pull request merged**
